const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { verifyPluginSource } = require('./verify-plugin-source');

test('source admission uses remote main and rejects an unmerged source commit', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-source-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const git = (cwd, ...args) => execFileSync('git', ['-C', cwd, ...args], { encoding: 'utf8', stdio: 'pipe' }).trim();
  const origin = path.join(root, 'origin');
  fs.mkdirSync(origin);
  git(origin, 'init', '-b', 'main');
  git(origin, 'config', 'user.name', 'Fixture');
  git(origin, 'config', 'user.email', 'test@example.invalid');
  git(origin, 'commit', '--allow-empty', '-m', 'main');
  const approved = git(origin, 'rev-parse', 'HEAD');
  git(origin, 'switch', '-c', 'unmerged');
  git(origin, 'commit', '--allow-empty', '-m', 'unreviewed');
  const unmerged = git(origin, 'rev-parse', 'HEAD');
  git(origin, 'switch', 'main');
  const clone = path.join(root, 'plugin');
  git(root, 'clone', origin, clone);
  verifyPluginSource(clone, approved);
  assert.throws(() => verifyPluginSource(clone, unmerged));
  assert.throws(() => verifyPluginSource(clone, 'a'.repeat(40)));
  assert.throws(() => verifyPluginSource(clone, 'main'), /full Plugin source commit/);
  git(origin, 'commit', '--allow-empty', '-m', 'next approved');
  verifyPluginSource(clone, git(origin, 'rev-parse', 'HEAD'));
  assert.equal(git(clone, 'rev-parse', 'HEAD'), approved);
});
